FROM python:3.10

WORKDIR /app

RUN mkdir configs
RUN mkdir sample_data
RUN mkdir modules

COPY requirements.txt ./
COPY som_main.py ./

COPY configs/* ./configs
COPY modules/* ./modules
COPY sample_data/* ./sample_data

RUN pip install -r requirements.txt

# CMD [ "python", "server.py" ]