apiVersion: v1
kind: Service
metadata:
  name: som-trainer
  namespace: default
  labels:
    app: som-trainer
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    name: som-trainer-grpc
  - port: 8081
    protocol: TCP
    name: som-trainer-http
  selector:
    app: som-trainer