kind: Service 
apiVersion: v1 
metadata:
  name: som-trainer-np-service
spec:
  type: NodePort
  selector:
    app: som-trainer
  ports:
    - name: port1
      nodePort: 30163
      port: 8080
      targetPort: 8080