name: Deploy SOM'

on:
  push:
    branches:
    - 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v2

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GKE_PROJECT }}
        service_account_key: ${{ secrets.GKE_SA_KEY }}

    - uses: 'google-github-actions/get-gke-credentials@v2'
      with:
        cluster_name: 'som-cluster'
        location: 'us-central1-a'
  
    - name: build and push the docker image

      env:
        GOOGLE_PROJECT: ${{ secrets.GKE_PROJECT }}
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev
        docker build -t us-central1-docker.pkg.dev/$GOOGLE_PROJECT/somapp/somimage:latest .
        docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT/somapp/somimage:latest

    - name: deploy to gke
      env:
        GOOGLE_PROJECT: ${{ secrets.GKE_PROJECT }}
      run: |
        kubectl apply -f som-k8s-gcp/resources.yaml