name: Deploy SOM

on:
  push:
    branches:
    - 'master'
env:
  DEPLOYMENT_NAME: gke-test
  PROJECT_ID: ${{ secrets.GKE_PROJECT_ID }}
  GKE_CLUSTER: cluster-som
  GKE_OZNE: us-central1-b
  ARTIFACT_REG_LOCATION: australia-southeast1
  ARTIFACT_REG_REPO: som-art-repo
  IMAGE: somimage 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v2

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        export_default_credentials: true
    - uses: 'google-github-actions/get-gke-credentials@v2'
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_OZNE }}
  
    - name: build and push the docker image

      run: |
        echo $ARTIFACT_REG_LOCATION-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REG_REPO/$IMAGE:latest
        gcloud auth configure-docker $ARTIFACT_REG_LOCATION-docker.pkg.dev
        docker build -t $ARTIFACT_REG_LOCATION-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REG_REPO/$IMAGE:latest .
        docker push $ARTIFACT_REG_LOCATION-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REG_REPO/$IMAGE:latest

    - name: deploy to gke
      run: |
        sed -i -e "s/ARTIFACT_REG_LOCATION/$ARTIFACT_REG_LOCATION/g" -e "s/PROJECT_ID/$PROJECT_ID/g" -e "s/ARTIFACT_REG_REPO/$ARTIFACT_REG_REPO/g" -e "s/IMAGE/$IMAGE/g" som-k8s-gcp/resources.yaml 
        kubectl apply -f som-k8s-gcp/resources.yaml